import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer";
import Nav from "./_components/Nav";
import FeaturesBar from "./_components/FeaturesBar";
import MySessionProvider from "./_Provider/MySessionProvider";
import { Toaster } from "sonner";
import CartContextProvider from "./_context/cartContextProvider";
import { getUseCart } from "./_actions/getUserCart";
import { getUseWishlist } from "./_actions/getUserWishlist";
import WishlistContextProvider from "./_context/WishlistContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userCart = await getUseCart();
  const userWishlist = await getUseWishlist();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MySessionProvider>
          <CartContextProvider userCart={userCart}>
            <WishlistContextProvider userWishlist={userWishlist}>
              <Nav />
              {children}
              <Toaster />
              <FeaturesBar />
              <Footer />
            </WishlistContextProvider>
          </CartContextProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}
